// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7QNG41GLGK2bd4ec_Ry6or-2LAzGG4I',
    appId: '1:507254107447:web:bd6a8035120900ab12beb2',
    messagingSenderId: '507254107447',
    projectId: 'showbox-116b2',
    authDomain: 'showbox-116b2.firebaseapp.com',
    storageBucket: 'showbox-116b2.appspot.com',
    measurementId: 'G-XDP161HBN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXKeK7U2cOW3gIaI89dg6opfyL4N9WOms',
    appId: '1:507254107447:android:f63ede6063023fe512beb2',
    messagingSenderId: '507254107447',
    projectId: 'showbox-116b2',
    storageBucket: 'showbox-116b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdqJBeBu6cp2zK3Wh4v0ascdmgxwAwBz4',
    appId: '1:507254107447:ios:af499e9062743cda12beb2',
    messagingSenderId: '507254107447',
    projectId: 'showbox-116b2',
    storageBucket: 'showbox-116b2.appspot.com',
    iosBundleId: 'com.example.showbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdqJBeBu6cp2zK3Wh4v0ascdmgxwAwBz4',
    appId: '1:507254107447:ios:af499e9062743cda12beb2',
    messagingSenderId: '507254107447',
    projectId: 'showbox-116b2',
    storageBucket: 'showbox-116b2.appspot.com',
    iosBundleId: 'com.example.showbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC7QNG41GLGK2bd4ec_Ry6or-2LAzGG4I',
    appId: '1:507254107447:web:3e207def56e063e612beb2',
    messagingSenderId: '507254107447',
    projectId: 'showbox-116b2',
    authDomain: 'showbox-116b2.firebaseapp.com',
    storageBucket: 'showbox-116b2.appspot.com',
    measurementId: 'G-G93GNGJN67',
  );
}
